/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EV3USBConnect_Connector */

#ifndef _Included_EV3USBConnect_Connector
#define _Included_EV3USBConnect_Connector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EV3USBConnect_Connector
 * Method:    readWrite
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_EV3USBConnect_Connector_readWrite
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     EV3USBConnect_Connector
 * Method:    write
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_EV3USBConnect_Connector_write
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
